package com.kinstalk.her.skillnews.components;

public enum PlayerState {
    STATE_PLAY_INTRODUCTION,
    STATE_PREPARE_TO_PLAY,
    MUSIC_STATE_IDLE,
    MUSIC_STATE_PLAYING,
    MUSIC_STATE_ONINIT,
    MUSIC_STATE_ONLOADING,
    MUSIC_STATE_ONPREPARED,
    MUSIC_STATE_ONPAUSE,
    MUSIC_STATE_ONSTOP,
    MUSIC_STATE_ONRESUME,
    MUSIC_STATE_ONCOMPLETION,
    MUSIC_STATE_ONERROR,
    MUSIC_STATE_ISPLAYING,
    MUSIC_STATE_LRCINFO,
    MUSIC_STATE_CURRENT,
    MUSIC_STATE_SEEKCOMPLETE
}
